server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /service-worker.js {
        try_files $uri =404;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location /_expo/static/ {
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }
}